from pathlib import Path
import json,hashlib,html
from datetime import datetime,timezone
R=Path(__file__).resolve().parent
files={
 'cardboard_box':{'selected':True,'original_tool_path':'/Users/admin/.codex/generated_images/01a09a46-f889-7fa1-a3f0-03f63ff9df3b/exec-b7c8a8df-6cb3-45f5-9e0f-ad2a4b72113e.png','reason':'Broad visible foot and top; square body with playful eyes.'},
 'fridge-rejected-narrow':{'selected':False,'original_tool_path':'/Users/admin/.codex/generated_images/01a09a46-f889-7fa1-a3f0-03f63ff9df3b/exec-890c4472-3106-4668-bfb8-5dc9eb1074ac.png','reason':'Rejected: width-to-height ratio about 0.57 remains too slender for the approved broad-foot experiment.'},
 'fridge':{'selected':True,'original_tool_path':'/Users/admin/.codex/generated_images/01a09a46-f889-7fa1-a3f0-03f63ff9df3b/exec-a98347e0-07b7-4db6-832c-e8357b99ca2c.png','reason':'Wider toy fridge, visible full-width plinth and top; uniformly scaled to 110 world units wide.'},
 'wood_plank-rejected-thin':{'selected':False,'original_tool_path':'/Users/admin/.codex/generated_images/01a09a46-f889-7fa1-a3f0-03f63ff9df3b/exec-c8405eaa-ecc4-4271-a9b8-7b198d48981f.png','reason':'Rejected: aspect ratio about 15.8 would yield an excessively thin plank at 260 world units width.'},
 'wood_plank':{'selected':True,'original_tool_path':'/Users/admin/.codex/generated_images/01a09a46-f889-7fa1-a3f0-03f63ff9df3b/exec-61c836f6-bd7e-43f9-96f6-9e642a0a8430.png','reason':'260-wide long level beam, about 28.7 units thick; blue flush anti-slip bands are visible.'},
}
source={'version':'difficulty-r1-art-frozen','date':'2026-09-13','tool':'built-in image_gen.imagegen','mode':'text-only generation; one asset per tool call','input_images_submitted':[],'local_files_uploaded':False,'source_policy':'New generated game candidates authorized by user; local original images were only viewed to understand style. No historical UI image was cut into these assets. No third-party image downloads. Not a replacement of the external formal-source archive.','generation_calls':[]}
for slug,entry in files.items():
 p=R/'generated'/f'{slug}.png'; prompt=R/'prompts'/f'{slug}.txt'
 source['generation_calls'].append({'id':slug,**entry,'saved_generated_file':str(p),'generated_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'prompt_file':str(prompt),'prompt':prompt.read_text(),'generation_options':'Built-in default; genuine transparent background requested; no reference-image inputs; no custom model or CLI','tool_parameters_exposed':['prompt']})
source['frozen_files']={str(p.relative_to(R)):hashlib.sha256(p.read_bytes()).hexdigest() for p in [R/'GEOMETRY.json',R/'GEOMETRY_CHECK.json',R/'PROCESSING_AUDIT.json',*sorted((R/'assets').glob('*.png'))]}
(R/'SOURCE.json').write_text(json.dumps(source,ensure_ascii=False,indent=2)+'\n')
g=json.loads((R/'GEOMETRY.json').read_text());qc=json.loads((R/'GEOMETRY_CHECK.json').read_text());cards=[]
for row,check in zip(g['assets'],qc['assets']):
 s=row['slug'];m=row['measurements'];cards.append(f'''<section><h2>{row['name']}</h2><div class="sprite"><img src="assets/object_{s}.png" alt="{row['name']}正式质量试玩候选"></div><dl><dt>物理宽 × 高</dt><dd>{row['width']:.2f} × {row['height']:.2f}</dd><dt>水平顶面 / 底面</dt><dd>{m['top']['width_world']:.2f} / {m['foot']['width_world']:.2f}</dd><dt>轮廓最大偏差</dt><dd>{check['boundary_distance_world']['max']:.3f} 世界单位</dd></dl><a href="{s}-geometry.png"><img class="geometry" src="{s}-geometry.png" alt="红色物理轮廓与蓝色承托平面"></a><p>红线：实际物理轮廓；蓝线：真实水平承托面。</p></section>''')
page='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>基础难度 R1 · 三件承托素材</title><style>body{margin:0;background:#edf4f9;color:#14344b;font:16px/1.6 system-ui,sans-serif}main{max-width:1180px;margin:32px auto;padding:0 22px}h1{font-size:28px}aside{background:#fff1d6;border-left:4px solid #efac2f;padding:14px 18px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px;margin:24px 0}section{background:#fff;border:1px solid #dae6ee;border-radius:14px;padding:20px}h2{margin:0 0 12px}.sprite{height:260px;display:flex;align-items:center;justify-content:center;background:#dfedf8;border-radius:8px}.sprite img{max-width:94%;max-height:240px;object-fit:contain}dl{display:grid;grid-template-columns:1fr 1fr;gap:4px;font-size:14px}dt,dd{margin:0}.geometry{width:100%;max-height:360px;object-fit:contain;background:#daeaf6}p{font-size:14px}a{color:#1267a1}@media(max-width:850px){.grid{grid-template-columns:1fr}}</style><main><h1>基础难度 R1 · 三件承托素材</h1><aside>这是已完成自身轮廓检查的正式质量试玩候选。主体由图像工具生成；本地只清理外部残片、裁切和提取轮廓。均按实际轮廓等比映射世界尺寸。引擎难度、质量与连接效果由本轮玩法实验另行验证。</aside><div class="grid">'''+''.join(cards)+'''</div><p>三件 NEXT 轮廓与对应 Sprite 的 alpha 逐像素一致。冰箱首张偏瘦、木板首张偏薄，因此已放弃；两张原图与原始提示词仍保留用于追溯。纸箱顶面约 77.5 单位，比名义 80–90 略短，保留真实可见顶缘，未扩大看不见的承托面。</p><p><a href="GEOMETRY.json">冻结几何</a> · <a href="GEOMETRY_CHECK.json">几何检查</a> · <a href="PROCESSING_AUDIT.json">本地处理审计</a> · <a href="SOURCE.json">生成来源与完整提示词</a></p></main></html>'''
(R/'index.html').write_text(page)
print(json.dumps({'source':str(R/'SOURCE.json'),'review':str(R/'index.html'),'geometry_hash':source['frozen_files']['GEOMETRY.json']},ensure_ascii=False))
