"""Preparation-only geometric candidates, never a physics validation result."""
from pathlib import Path
import json,hashlib
from PIL import Image
R=Path(__file__).resolve().parents[2];P=R/'preparation';a=R/'assets/batch0/art'
scale_path=P/'art/OBJECT_GAMEPLAY_SCALE.reference.json';scales=json.loads(scale_path.read_text())
rows=[]
for slug in ['cardboard_box','wood_plank','basketball','fridge']:
 spec=next(o for o in scales['objects'] if o['slug']==slug);im=Image.open(a/('object_'+slug+'.png'));x0,y0,x1,y1=im.getbbox();w=spec['gameplay_scale']['width_u']*100;h=spec['gameplay_scale']['height_u']*100
 ratio=max(w/(x1-x0),h/(y1-y0))
 rows.append({'slug':slug,'name':spec['name'],'gameplay_scale':spec['gameplay_scale'],'units_per_u':100,'shape':'circle' if slug=='basketball' else 'box','size_world':[w,h],'radius_world':w/2 if slug=='basketball' else None,'sprite_source':'assets/batch0/art/object_'+slug+'.png','sprite_sha256':hashlib.sha256((a/('object_'+slug+'.png')).read_bytes()).hexdigest(),'source_alpha_bounds_px':[x0,y0,x1,y1],'sprite_scale_candidate':ratio,'sprite_size_world':[im.width*ratio,im.height*ratio],'grip_local_world':[0,h/2],'status':'geometry_candidate_not_physics_tested'})
box=Image.open(a/'object_cardboard_box.png');bx=box.getbbox();platform=Image.open(a/'platform_city_base.png');px=platform.getbbox();bw=184*(bx[2]-bx[0])/box.width;pw=280*(px[2]-px[0])/platform.width
report={'status':'preparation_geometry_candidates_only','scale_source_sha256':hashlib.sha256(scale_path.read_bytes()).hexdigest(),'objects':rows,'initial_baseline':{'status':'accepted_for_first_calibration_not_physics_verified','approved_visual_platform_width_in_box_widths':pw/bw,'platform_width_u':1.6,'approved_visual_drop_gap_u_approx':(974-(152+184*297/299))/bw,'release_position':'Follow approved R6; visual gap estimate is not measured Collider clearance.', 'retired_defaults':'4.2u platform and 1.8u clearance are no longer active defaults.', 'rule':'Use SPEC 2.2; validate support and rotation in Batch 1A; no hidden wider support.'},'not_verified':['support footprint matching','mass and center of mass','claw three-state attachment','rotation clearance','fixed step behavior','material friction and restitution','landing stability']}
(P/'calibration/GEOMETRY_CANDIDATES.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
cards=[]
for row in rows:
 slug=row['slug'];w,h=row['size_world'];iw,ih=row['sprite_size_world'];factor=1.7;im=Image.open(a/('object_'+slug+'.png'));x0,y0,x1,y1=row['source_alpha_bounds_px'];ratio=row['sprite_scale_candidate'];left=200-(x0+x1)/2*ratio*factor;top=150-(y0+y1)/2*ratio*factor
 shape=f'width:{w*factor}px;height:{h*factor}px;left:{200-w*factor/2}px;top:{150-h*factor/2}px;'+('border-radius:50%;' if row['shape']=='circle' else '')
 cards.append(f'''<section><h2>{row['name']}</h2><div class="stage"><img src="../../{row['sprite_source']}" style="left:{left}px;top:{top}px;width:{iw*factor}px;height:{ih*factor}px"><div class="collider" style="{shape}"></div><div class="grip" style="left:196px;top:{146-h*factor/2}px"></div></div><p>正式比例 {w/100:g}u × {h/100:g}u · {'圆' if row['shape']=='circle' else '矩形'}候选</p><p>绿色：拟议物理轮廓　黄色：顶部挂点</p></section>''')
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>四物体几何校准候选</title><style>*{box-sizing:border-box}body{margin:0;padding:28px;background:#edf4f9;color:#193b56;font:16px/1.7 system-ui}main{max-width:920px;margin:auto}h1{font-size:26px}.notice{padding:14px;background:#fff1cd;border-left:4px solid #e2ac3b}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:20px}section{background:white;border-radius:14px;padding:14px;overflow:hidden}h2{font-size:19px;margin:0}p{margin:4px 0;font-size:14px}.stage{position:relative;width:400px;height:300px;background:#deebf6;overflow:hidden}.stage img{position:absolute}.collider{position:absolute;border:2px solid #0b9a55;background:#24bd7012}.grip{position:absolute;width:8px;height:8px;border-radius:50%;background:#ffcd28;border:1px solid #7a5f00}a{color:#0874be}@media(max-width:800px){.grid{grid-template-columns:1fr}}</style><main><h1>四物体几何校准候选</h1><div class="notice">这是 R2 开发前几何候选，保留作历史对照；当前 1A 已改用校准后的凸轮廓/圆。<a href="contact-review.html">查看当前接触对照与录屏</a>。本页绿色线不代表当前运行 Collider。</div><p>1u = 100 世界单位。四物体使用同一尺度，碰撞轮廓与美术投影分开检查。</p><div class="grid">'''+''.join(cards)+'''</div><h2>已统一的首轮参数</h2><p>已同意采用 1.6u 承台首轮候选，释放位置沿用 R6。构图估计空隙约 3.67u，实际 Collider 间隙仍须在 Batch 1A 量测。旧 4.2u 承台与 1.8u 间隙已退役；不使用不可见宽支撑。</p><p>当前 1A 已恢复，并按用户确认修正镜头与接触。全塔保持真实模拟；本页保留旧候选，现状以 contact-review.html 和 BATCH1A_ACCEPTANCE.md 为准。</p><h2>对抗式检查</h2><p>木板：桥接是否真由薄矩形支撑；冰箱：圆润透视侧面不能直接当物理宽高；篮球：真正滚动；纸箱：偏心堆叠。挂点、旋转间隙与碰撞底面还需实际引擎验证。</p><p><a href="engine.html">已确认的实际视觉</a> · <a href="../calibration/GEOMETRY_CANDIDATES.json">候选尺寸与来源</a></p></main></html>'''
(P/'review/geometry.html').write_text(html)
print(json.dumps(report['initial_baseline'],ensure_ascii=False))
